var translate ={
    "coe" :{
		"home":{
			"period"             : "Qualification Period",
			"title"              : "Circle of Excellence 2018",
			"labelsTable"        : {
				"PSNC500"    : "Personally Sponsored New Consultants with $500*",
				"GOMT"       : "Grow or Maintain Title",
				"CDPRS"      : "Central Distric Paid Retail Sales",
				"ACDPRSG"    : "Central District Paid Retail Sales Growth",
				"PIBFLCD"    : "Promote an Indirect Branch** (First Level - from Central District)",
				"ETIPBP"     : "Each Time Indirectly promoted Branch performs",
				"PDB"        : "Promote a Dirct Branch**",
				"ETDPBP"     : "Each Time Directly promoted Branch performs",
				"ACBNC500"   : "Central Branch New Consultants with $500*",
				"CBNCM"      : "Central Branch New Consultants who achieve $500 in 1st or 2nd month, and achieve $500 the following month",
				"EMCDOG"     : "Every month you meet your Central District # of Orders Goal",
				"AGCDABG"    : "Growth Central District Active Base Growth from December 1, 2017 - August 1, 2018",
				"PSC500"     : "Personally Sponsored Consultants with $500*",
				"PSC500FM"   : "Personally Sponsored Consultants with $500 the following month",
				"DCDPRSG"    : "Central District Paid Retail Sales Goal",
				"CDAS"       : "Central District Actual Sales",
				"CDG"        : "Central District Growth",
				"NIB"        : "New Indirect Branches** (1st level - from Central District)",
				"NIBP"       : "New Indirect Branches performing",
				"NDB"        : "New Direct Branches",
				"NDBP"       : "New Direct Branches performing",
				"CBNC500"    : "Central Branch New Consultants with $500",
				"CBNC500FM"  : "Central Branch New Consultants with $500 the following month",
				"CDO"        : "Central District # of Orders",
				"CDAB"       : "Central District Active Base",
				"CDPRSG"     : "Central District Paid Retail Sales Growth",
				"PNIB"       : "New Indirect Branches** (1st level - from Central District)",
				"PNIBP"      : "New Indirect Branches performing",
				"PNDB"       : "New Direct Branches**",
				"PNDBP"      : "New Direct Branches performing",
				"PCBNC500"   : "Central Branch New Consultants with $500",
				"PCBNC500FM" : "Central Branch New Consultants with $500 the following month",
				"CDOG"       : "Central District Orders Goal",
				"CDABG"      : "Central District Active Base Growth from Dec 1st 2017 to Aug 1st 2018"			
			}
		}
	},
    "summer": {
        "activity": {
			"btnRoyalty"         : "Regresar a JAFRARoyalty.com",
            "title"              : "Viaje de verano 2018",
            "subtitle"           : "Actividad hasta: %bm %bd, %by",
			"consId"             : "# de Consultora:",
			"consName"           : "Nombre:",
			"currTitle"          : "Título de Pago Actual:",
			"tripLevAch"         : "Nivel Alcanzado para Viaje:",
			"ambLevAch"          : "Nivel EMB alcanzado:",
			"level"              : "Nivel",
			"pointsNeeded"       : "Puntos necesarios",
			"earn"               : "Gana",
			"summerTrip"         : "Viaje de Verano!",
			"personalSpon"       : "Patrocinio Directo",
			"personalSponThead1" : "Nuevas Consultoras Personalmente Patrocinadas Dic 1 - May 31",
			"personalSponThead2" : "Nuevas Consultoras con $500 en su primer o segundo mes",
			"personalSponThead3" : "Nuevas Consultoras Emprendedoras",
			"earnPoints"         : "Actividades para ganar puntos",
			"points"             : "Puntos",
			"receiveGifts"       : "Regalos",
			"details"            : "Detalles",
			"qtitle"             : "Título de pago al 1 de Diciembre de 2017:",
			"pointsEarnedTrip"   : "Puntos ganados para el viaje a la fecha:",
			"achieved10BB"       : "Lograste 10 Consultoras Emprendedoras?",
			"achievedCDGrowth"   : "Lograste Crecimiento DC?",
			"tripLevelAchieved"  : "Nivel de viaje alcanzado",
			"ambLevelAchieved"   : "Nivel de embajadora alcanzado",
			"BB"                 : "CE", 
			"btnAmb"             : "Seguimiento Embajadoras",
			"titleConsId"        : "Por favor, coloca tu número de consultora",
			"toParticipate"      : "Para participar, se deben cumplir requerimientos mínimos:",
			"requirementsCON"    : "Patrocinar por lo menos 10 Nuevas Consultoras que logren el estatus de Consultora Emprendedora durante el periodo de calificación",
			"requirementsALL"    : "Crecer las Ventas Pagadas al Precio Público del Districo Central<br />Patrocinar por lo menos 10 Nuevas Consultoras que logren el estatus de Consultora Emprendedora durante el periodo de calificación",
			"eaSumTrip"          : {
				"PT"             : "Purple Tote",
				"OTDN"           : "Orange Tote Drop Note",
				"PL"             : "Purple Luggage",
				"TLO"            : "Viaje para Ti (solo Hotel)",
				"AIT"            : "Viaje y boleto de avión para ti",
				"AITLFG"         : "Viaje y boleto de avión para ti y Viaje para un invitado (solo hotel)",
				"PCC"            : "Purple Carrying Case"
			},
			"activitiesToEarn"   : {
				"PQNC"           : "Consultoras Calificadas",
				"PBB"            : "Consultoras Emprendedoras Personales",
				"MPR"            : "Ventas personales mensuales"
			},
			"tripLevelAchi"      : {
				"IN_PROGRESS"    : "En progreso",
				"COMPLETED"      : "Alcanzado",
				"YES"            : "Si",
				"NO"             : "No"				
			}
        },
		"activityDeta":{
			"return"               : "Regresar",
			"dateQ"                : "Título de pago al 1 de Diciembre de 2017:",
			"personalAct"          : "Actividad Personal",
			"activity"             : "Actividad",
			"december"             : "Dic",
			"january"              : "Ene",
			"february"             : "Feb",
			"march"                : "Mar",
			"april"                : "Abr",
			"may"                  : "May",
			"total"                : "Total",
			"pointsEarned"         : "Puntos ganados",
			"centralDistrictSales" : "Ventas Distrito Central",
			"actiPersonal"         : {
				"PQNC"             : "Consultoras Calificadas ($500)",
				"PBB"              : "Consultoras Emprendedoras Personales",
				"MPRS"             : "Ventas personales mensuales",
				"TP"               : "Puntos totales",
				"CDPRSG"           : "Meta de Ventas Pagadas al Precio Público en el DC",
				"AS"               : "Ventas actuales",
				"TGW"              : "Crecimiento"
			}			
		},
		"sponsor"                : {
			"title"              : "Actividad Personal - Nuevas consultoras patrocinadas",
			"tconsId"            : "# de Cons",
			"tname"              : "Nombre",
			"tphone"             : "Teléfono",
			"temail"             : "Correo Electrónico",
			"tstartDate"         : "Fecha de Inicio",
			"tentryDate"         : "Logró NCC $500",
			"tretailSales"       : "Total de Ventas al Precio Público",
			"tBB"                : "Logró Consultora Emprendedora"
		},
		"central"                : {
			"title"              : "Ventas / Patrocinios en el Distrito Central",
			"tleaderID"          : "# ID de Líder",
			"tname"              : "Nombre",
			"tphone"             : "Teléfono #",
			"temail"             : "Correo Electrónico",
			"tNewConsSponCB"     : "# de Nuevas Consultoras Patrocinadas en el Grupo Central",
			"tBBinCB"            : "Nuevas Consultoras Emprendedoras en el Grupo Central"
		},
		"district"               : {
			"title"              : "Distrito Total - Patrocinios por nivel de linaje",
			"tLineageLev"        : "Nivel de Linaje",
			"tNewCons"           : "Nuevas Consultoras Patrocinadas",
			"tBB"                : "Nuevas Consultoras Emprendedoras"
		},
		"amb"                    : {
			"earnSummerTrip"     : "Embajadoras ganan un viaje de verano!",
			"achieveTotalGoals"  : "Achieve Total District Goals",
			"earn"               : "Gana",
			"level1"             : "Nivel 1",
			"level2"             : "Nivel 2",
			"level1Price"        : "Viaje y boleto de avión para ti",
			"level2Price"        : "Viaje y boleto de avión para ti y Viaje para un invitado",
			"personalActi"       : "Actividad Personal",
			"newConsPerSpon"     : "Nuevas Consultoras Personalmente Patrocinadas Ene 1 - May 31",
			"businessBuilder"    : "Consultoras Emprendedoras",
			"totDisActi"         : "Actividad Distrito Total (Para Embajadoras)",
			"totDistrict"        : "Distrito Total",
			"numBB"              : "# de Consultoras Emprendedoras *",
			"goals"              : "Objetivos",
			"level1"             : "Nivel 1",
			"level2"             : "Nivel 2",
			"newConsSponJanMay"  : "Nuevas consultoras patrocinadas Dic 1 - May 31",
			"BB"                 : "Consultoras Emprendedoras",
			"note"               : "* Para esta promoción, una Consultora Emprendedora es aquella que es patrocinada del 1 de diciembre de 2017 al 31 de mayo de 2018 y logra acumular $1,500 en Ventas Personales Pagadas al Precio Público.",
			"btnAmb"             : "Gráfica de Embajadoras"
		},
		"lineage"                : {
			"title"              : "Distrito Total - Patrocinios por nivel de linaje:",
			"tLineageLev"        : "Nivel",
			"tLeaderID"          : "# ID de Líder",
			"tName"              : "Nombre",
			"tTitle"             : "Título",
			"tPhone"             : "Teléfono",
			"tEmail"             : "Correo Electrónico",
			"tUpline"            : "Líder Ascendente",
			"tNewCons"           : "# de Nuevas Consultoras Patrocinadas en el GC",
			"tBB"                : "Nuevas Consultoras Emprendedoras en el GC"
		},
		"board"                  : {
			"title"              : "Gráfica de Embajadoras",
			"lLevel1"            : "% alcanzado nivel 1",
			"lLevel2"            : "% alcanzado nivel 2"
		}
	},
	"commons" : {
		"timeToLoad"        : "Cargando... por favor espere",
		"tooTimeToLoad"     : "Está tomando mucho tiempo en cargar, por favor espere",
		"titles"            : {
			"CON"           : "CON",
			"MGR"           : "SUP",
			"DM1"           : "SD1",
			"DM2"           : "SD2",
			"DM3"           : "SD3",
			"DD1"           : "DD1",
			"DD2"           : "DD2",
			"DD3"           : "DD3",
			"DD4"           : "DD4",
			"DD5"           : "DD5",
			"DDE"           : "DED",
			"DDN"           : "DND",
			"AMB"           : "EMB"			
		}
	}
	

}
