var translate = {
    "coe" :{
		"home":{
			"period"             : "Qualification Period",
			"title"              : "Circle of Excellence 2018",
			"labelsTable"        : {
				"PSNC500"    : "Personally Sponsored New Consultants with $500*",
				"GOMT"       : "Grow or Maintain Title",
				"CDPRS"      : "Central Distric Paid Retail Sales",
				"ACDPRSG"    : "Central District Paid Retail Sales Growth",
				"PIBFLCD"    : "Promote an Indirect Branch** (First Level - from Central District)",
				"ETIPBP"     : "Each Time Indirectly promoted Branch performs",
				"PDB"        : "Promote a Dirct Branch**",
				"ETDPBP"     : "Each Time Directly promoted Branch performs",
				"ACBNC500"   : "Central Branch New Consultants with $500*",
				"CBNCM"      : "Central Branch New Consultants who achieve $500 in 1st or 2nd month, and achieve $500 the following month",
				"EMCDOG"     : "Every month you meet your Central District # of Orders Goal",
				"AGCDABG"    : "Growth Central District Active Base Growth from December 1, 2017 - August 1, 2018",
				"PSC500"     : "Personally Sponsored Consultants with $500*",
				"PSC500FM"   : "Personally Sponsored Consultants with $500 the following month",
				"DCDPRSG"    : "Central District Paid Retail Sales Goal",
				"CDAS"       : "Central District Actual Sales",
				"CDG"        : "Central District Growth",
				"NIB"        : "New Indirect Branches** (1st level - from Central District)",
				"NIBP"       : "New Indirect Branches performing",
				"NDB"        : "New Direct Branches",
				"NDBP"       : "New Direct Branches performing",
				"CBNC500"    : "Central Branch New Consultants with $500",
				"CBNC500FM"  : "Central Branch New Consultants with $500 the following month",
				"CDO"        : "Central District # of Orders",
				"CDAB"       : "Central District Active Base",
				"CDPRSG"     : "Central District Paid Retail Sales Growth",
				"PNIB"       : "New Indirect Branches** (1st level - from Central District)",
				"PNIBP"      : "New Indirect Branches performing",
				"PNDB"       : "New Direct Branches**",
				"PNDBP"      : "New Direct Branches performing",
				"PCBNC500"   : "Central Branch New Consultants with $500",
				"PCBNC500FM" : "Central Branch New Consultants with $500 the following month",
				"CDOG"       : "Central District Orders Goal",
				"CDABG"      : "Central District Active Base Growth from Dec 1st 2017 to Aug 1st 2018"			
			}
		}
	},
    "summer": {
        "activity": {
			"btnRoyalty"         : "Return to JAFRARoyalty.com",
            "title"              : "Summer Trip 2018",
            "subtitle"           : "Activity as of: %bm %bd, %by",
			"consId"             : "Consultant ID:",
			"consName"           : "Consultant Name:",
			"currTitle"          : "Current Title:",
			"tripLevAch"         : "Trip Level Achieved:",
			"ambLevAch"          : "AMB Level Achieved:",
			"level"              : "Level",
			"pointsNeeded"       : "Points Needed",
			"earn"               : "Earn",
			"summerTrip"         : "Summer Trip!",
			"personalSpon"       : "Personal Sponsoring",
			"personalSponThead1" : "New Consultants Personally Sponsored Dec 1 - May 31",
			"personalSponThead2" : "New Consultants with $500 in 1st or 2nd month",
			"personalSponThead3" : "Business Builder Consultants",
			"earnPoints"         : "Activities to Earn Points",
			"points"             : "Points",
			"receiveGifts"       : "Receive Gifts",
			"details"            : "Details",
			"qtitle"             : "December 1, 2017 Title (Qualifying Title):",
			"pointsEarnedTrip"   : "Points earned Trip To Date:",
			"achieved10BB"       : "Achieved 10 Business Builders?",
			"achievedCDGrowth"   : "Achieved CD Growth?",
			"tripLevelAchieved"  : "Trip Level achieved",
			"ambLevelAchieved"   : "AMB Level achieved",
			"BB"                 : "BB",   
			"btnAmb"             : "AMB Leader Tracking",
			"titleConsId"        : "Please, enter your consultant ID",
			"toParticipate"      : "Minimum Requirements to participate:",
			"requirementsCON"    : "Sponsor at least 10 New Consultants who achive Business Builder Status during qualification period.",
			"requirementsALL"    : "Grow Central District Paid Retail Sales<br />Sponsor at least 10 New Consultants who achive Business Builder during qualification period",
			"eaSumTrip"          : {
				"PT"             : "Purple Tote",
				"OTDN"           : "Orange Tote Drop Note",
				"PL"             : "Purple Luggage",
				"TLO"            : "Trip (Land Only)",
				"AIT"            : "All inclusive Trip",
				"AITLFG"         : "All inclusive Trip + Land for Guest",
				"PCC"            : "Purple Carrying Case"
			},
			"activitiesToEarn"   : {
				"PQNC"           : "Personal QNCs",
				"PBB"            : "Personal Business Builders",
				"MPR"            : "Monthly Personal Retail"
			},
			"tripLevelAchi"      : {
				"IN_PROGRESS"    : "In Progress",
				"COMPLETED"      : "Achieved",
				"YES"            : "Yes",
				"NO"             : "No"				
			}
			
        },
		"activityDeta":{
			"return"               : "Back",
			"dateQ"                : "December 1, 2017 Title (Qualifying Title):",
			"personalAct"          : "Personal Activity",
			"activity"             : "Activity",
			"december"             : "Dec",
			"january"              : "Jan",
			"february"             : "Feb",
			"march"                : "Mar",
			"april"                : "Apr",
			"may"                  : "May",
			"total"                : "Total",
			"pointsEarned"         : "Points Earned",
			"centralDistrictSales" : "Central District Sales",
			"actiPersonal"         : {
				"PQNC"             : "Personal QNCs ($500)",
				"PBB"              : "Personal Business Builders",
				"MPRS"             : "Monthly Personal Retail Sales",
				"TP"               : "Total Points",
				"CDPRSG"           : "CD Paid Retail Sales Goals",
				"AS"               : "Actual Sales",
				"TGW"              : "Growth"
			}			
		},
		"sponsor"                : {
			"title"              : "Personal Activity - New Consultants Sponsored",
			"tconsId"            : "Cons ID",
			"tname"              : "Name",
			"tphone"             : "Phone #",
			"temail"             : "Email",
			"tstartDate"         : "Start Date",
			"tentryDate"         : "Achieved QNC $500",
			"tretailSales"       : "Total Retail Sales",
			"tBB"                : "Achieved Business Builder"	
		},
		"central"                : {
			"title"              : "Central District Sales / Sponsoring",
			"tleaderID"          : "Leader ID",
			"tname"              : "Name",
			"tphone"             : "Phone #",
			"temail"             : "Email",
			"tNewConsSponCB"     : "New Cons Sponsored in Central Branch",
			"tBBinCB"            : "Business Builders in Central Branch"
		},
		"district"               : {
			"title"              : "Total District - Sponsoring Activity By Lineage Levels",
			"tLineageLev"        : "Lineage Level",
			"tNewCons"           : "New Consultants Sponsored",
			"tBB"                : "Business Builders"
		},
		"amb"                    : {
			"earnSummerTrip"     : "Ambassadors Earn Summer Trip!",
			"achieveTotalGoals"  : "Achieve Total District Goals",
			"earn"               : "Earn",
			"level1"             : "Level 1",
			"level2"             : "Level 2",
			"level1Price"        : "All Inclusive Trip for Self",
			"level2Price"        : "All inclusive Trip for Self & Guest",
			"personalActi"       : "Personal Activity",
			"newConsPerSpon"     : "New Consultants Personally Sponsored Jan 1 - May 31",
			"businessBuilder"    : "Business Builder Consultants",
			"totDisActi"         : "Total District Activity (for Ambassadors)",
			"totDistrict"        : "Total District",
			"numBB"              : "# of Business Builders *",
			"goals"              : "Goals",
			"level1"             : "Level 1",
			"level2"             : "Level 2",
			"newConsSponJanMay"  : "New Consultants Sponsored Dec 1 - May 31",
			"BB"                 : "Business Builder",
			"note"               : "* For this promotion a Business Builder is a Consultant who is sponsored between December 1st 2017 and May 31st, 2018 who each achieve $1500 in ordered retail sales",
			"btnAmb"             : "Ambassador Leader Board"
		},
		"lineage"                : {
			"title"              : "Total District - Sponsoring Activity By Lineage Levels:",
			"tLineageLev"        : "Level",
			"tLeaderID"          : "Leader ID",
			"tName"              : "Name",
			"tTitle"             : "Title",
			"tPhone"             : "Phone #",
			"tEmail"             : "Email",
			"tUpline"            : "Upline Leader",
			"tNewCons"           : "New Cons Sponsored in CB",
			"tBB"                : "Business Builders in CB"
		},
		"board"                  : {
			"title"              : "Ambassador Leader Board",
			"lLevel1"            : "Level 1 % Achieved",
			"lLevel2"            : "Level 2 % Achieved"
		}
	},
	"commons" : {
		"timeToLoad"        : "Loading... please wait",
		"tooTimeToLoad"     : "It's taking a long time to load, please wait",
		"titles"            : {
			"CON"           : "CON",
			"MGR"           : "MGR",
			"DM1"           : "DM1",
			"DM2"           : "DM2",
			"DM3"           : "DM3",
			"DD1"           : "DD1",
			"DD2"           : "DD2",
			"DD3"           : "DD3",
			"DD4"           : "DD4",
			"DD5"           : "DD5",
			"DDE"           : "DDE",
			"DDN"           : "DDN",
			"AMB"           : "AMB"			
		}
	}

}